import { Sriracha } from "next/font/google";
import "./globals.css";

const sriracha = Sriracha({subsets: ['latin'], weight: '400'});

export const metadata = {
  title: "The Heat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sriracha.className}>{children}</body>
    </html>
  );
}
