import { Sriracha } from "next/font/google";
import { Sora } from "next/font/google";
import "./globals.css";

const sriracha = Sriracha({subsets: ['latin'], weight: '400'});
const sora = Sora({weight: '800', variable: '400', subsets: ['latin']})

export const metadata = {
  title: "The Heat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>{children}</body>
    </html>
  );
}
